### ISSUE TITLE
Add more output sizes

### ISSUE THREAD

**Issue by SmilerRyan** [makitsune/MakiScreen#1]
As of version 1.0, there are 7 item frames added/replaced however only 2 of these are used.
Changing the utput resolution only renders the same size (128x128 per map, on two maps) for one output.
Making use of the remaining maps to make a 2x3 would be a nice feature, and allow more clarity of the screen.

**Comment by towgenik** [comment]
we added in #3 option in `config.yml` 
1 = 256x128 = 2 maps
2 = 512x256 = 8 maps
3 = 1024x512 = 32 maps
we try increasing the resolution more but it eats so much data that the output itself gets corrupted, we try increasing `-qscale:v 1` value it helps a bit, but it still will send players so much packet that some players will caped their internet bill in less than a half an hours.
if you like to increase the resolution to more than 1024x512, you edit this file
https://github.com/makitsune/MakiScreen/blob/master/src/main/java/cat/maki/MakiScreen/ConfigFile.java
