### ISSUE TITLE
Very performance pulling

### ISSUE THREAD

**Issue by LPTP1Dev** [makitsune/MakiScreen#2]
I am trying to get this running on my test server (I'm streaming to the server using its domain) but I have some performance problems (only 13 tps and the map is lagging a bit, see attachments).  

How can I fix this? MC Server has 2 GB RAM and is not even using half of them. Running the server without MakiScreen fixes the performance issue.

Server: 1.16.4 Spigot
RAM: 2 GB

https://user-images.githubusercontent.com/51876648/119264950-5309fb00-bbe5-11eb-9b3a-51067ef791e6.mp4

![tps](https://user-images.githubusercontent.com/51876648/119264929-3c63a400-bbe5-11eb-8cdc-01f0baf6c52d.png)

**Comment by makinori** [comment]
Ah thats sucks sorry. This project was an experiment and probably not going to touch it again. I'm not sure how to help.

**Comment by LPTP1Dev** [comment]
I found out its a problem with ffmpeg / ig my PC config cause if my friend is streaming to the server its working perfect (ok tps is still low but fine) I tried playing around with some ffmpeg args, if I remove the `-qscale:v 1` its running less laggy but results into an less clear stream on the map, if I force ffmpeg to use an higher stream bitrate its getting better a bit and if I select the cmd window instead of the minecraft window (in obs) the laggs are nearly gone, maybe you can help me finding an better ffmpeg command since I'm no ffmpeg pro?

**Comment by LPTP1Dev** [comment]
Sent you an Discord FR btw so if you want we can write over Discord

**Comment by towgenik** [comment]
We fix it in #3. If you need to improve your performance a bit more, you can lower your resolution in `config.yml` and increase `-qscale:v` value from 1-31. also, if you had a flashing item frame when the player didn't hold or have the map in their inventory, you can try replacing the item frame with an invisible item frame, or use a texture pack that hides the item frame entirely.
